/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const express = require("express");
const bodyParser = require("body-parser");

const app = express();
let todos = [];
app.use(bodyParser.json());
//this is api for get all todos
/*
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
  
  */
app.get("/todos", (req, res) => {
  res.status(200).json({
    todos,
  });
});
//This is api for get todos with id
/*
   2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
  
*/
app.get("/todos/:id", (req, res) => {
  const { id } = req.params;
  const todo = todos.find((item) => {
    return item.id == id;
  });

  if (!todo) {
    return res.status(404).json({
      message: "TODO Not Found",
    });
  }
  res.status(200).json({
    todo,
  });
});
// this is api for add  new todo in todos array
/**
 3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
 */
app.post("/todos", (req, res) => {
  const { title, completed, description } = req.body;
  let id = 1;
  if (todos.length > 0) {
    id = todos[todos.length - 1].id + 1;
  }
  const todo = {
    id,
    title,
    completed,
    description,
  };
  //now push each todo in todos array
  todos.push(todo);
  res.status(201).json({ todos });
});
//
/*
4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true } 
*/
app.put("/todos/:id", (req, res) => {
  const { id } = req.params;
  const index = todos.findIndex((item) => item.id == id);

  if (index === -1) {
    return res.status(404).json({ message: "Todo not found" });
  }

  // Update whole object
  todos[index] = {
    ...todos[index],
    ...req.body,
  };

  return res.status(200).json({
    message: "Todo updated successfully",
    todo: todos[index],
  });
});
/*
5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123
 */
app.delete("/todos/:id", (req, res) => {
  const { id } = req.params;
  const todo = todos.find((item) => {
    return item.id == id;
  });
  if (!todo) {
    res.status(404).json({
      message: "todo not found",
    });
  }
});

const PORT = 3000;
app.listen(PORT, () => {
  console.log(`server is running on port ${PORT} || http:localhost:${PORT}`);
});
module.exports = app;
